// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbZ-qZp04VLOdTksR0hAxtWPQidpuFfU0',
    appId: '1:77773516092:web:e43e8f26c24ebfe09ac239',
    messagingSenderId: '77773516092',
    projectId: 'food-delivery-app-f2aff',
    authDomain: 'food-delivery-app-f2aff.firebaseapp.com',
    storageBucket: 'food-delivery-app-f2aff.firebasestorage.app',
    measurementId: 'G-0M0L5ZZ416',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYJ1qQR7vrGgzyr9HWFUa1lGSIKPfdIec',
    appId: '1:77773516092:android:2097064cb3bd62d29ac239',
    messagingSenderId: '77773516092',
    projectId: 'food-delivery-app-f2aff',
    storageBucket: 'food-delivery-app-f2aff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNiFXnCt65AANW-Y2bnO_9vPtZ93Qydwo',
    appId: '1:77773516092:ios:dae55531bc07ce5c9ac239',
    messagingSenderId: '77773516092',
    projectId: 'food-delivery-app-f2aff',
    storageBucket: 'food-delivery-app-f2aff.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNiFXnCt65AANW-Y2bnO_9vPtZ93Qydwo',
    appId: '1:77773516092:ios:dae55531bc07ce5c9ac239',
    messagingSenderId: '77773516092',
    projectId: 'food-delivery-app-f2aff',
    storageBucket: 'food-delivery-app-f2aff.firebasestorage.app',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbZ-qZp04VLOdTksR0hAxtWPQidpuFfU0',
    appId: '1:77773516092:web:1ea224378da582749ac239',
    messagingSenderId: '77773516092',
    projectId: 'food-delivery-app-f2aff',
    authDomain: 'food-delivery-app-f2aff.firebaseapp.com',
    storageBucket: 'food-delivery-app-f2aff.firebasestorage.app',
    measurementId: 'G-251E9QEBYM',
  );
}
